### ISSUE TITLE
Tutorial Notebook - End-to-end modeling baseline

### ISSUE THREAD

**Issue by ejhumphrey** [cosmir/openmic-2018#10]
This notebook will demonstrate how to model the data from start to finish:
- [x] Partition the data using the predefined splits
- [x] Train a basic sklearn model (Random Forest?)
- [x] Compute evaluation measures for train and test
- [x] Visualize micro / macro statistics
- [x] Compute VGGish features from audio
- [x] Perform end-to-end prediction

@bmcfee similar to #9, feel free to add checklist items

**Comment by simondurand** [comment]
First iteration pushed to `https://github.com/cosmir/openmic-2018/tree/durand/baseline`.
It still needs quite a lot of polishing but should run smoothly.

**Comment by bmcfee** [comment]
update: nb has had some polish.  i consider it sufficient at this point ; could use some plots, but good enough for now.
