### ISSUE TITLE
Create TGZ of data

### ISSUE THREAD

**Issue by ejhumphrey** [cosmir/openmic-2018#5]
Contains the following:

- [x] 20k audio files (2.4GB)
- [x] Audio file checksums in a text file
- [x] 20k VGGish feats JSON files (Schema: `{features: shape=[10, 128], time_points: len=10}`)
- [x] JSON file checksums in a text file
- [x] Track metadata CSV file
- [x] Aggregated labels in a CSV file (Schema `(sample_key: String, instrument: String, affinity: Float [0, 1], num_responses: int)` )
- [x] Individual labels in a CSV file
- [x] NOT INCLUDED: annotator ID map
- [x] Helper Class Map JSON file (Schema: `{instrument: idx: Int}`)
- [x] Partition directory like  `train00.csv, test00.csv`
- [x] Helper / convenience data: NPZ with four keys `X, Y_true (continuous in [0, 1]), Y_mask (binary: was labeled), sample_key`

```bash
openmic-2018/
  audio/
    checksums.txt
    NNN/
      NNN123.ogg
      ..
    NNM/
      NNM456.ogg
      ..
    ..
  vggish/
    checksums.txt
    NNN/
      NNN123.json
      ..
    NNM/
      NNM456.json
      ..
    ..
  metadata.csv
  sparse-labels.csv
  class-map.json
  partitions
    train00.txt
    test00.txt
    ..
  openmic-2018.npz 
```
@bmcfee @simondurand plz chime in with feedback!

**Comment by simondurand** [comment]
@ejhumphrey 
Blocked for now, but in the meantime, could you provide the link for the latest version of:
- 20k audio files (2.4GB)
- 20k VGGish feats JSON file
- Track metadata CSV file
- Sparse labels
as well as letting me know what needs to be corrected in this. For instance, I think the number of responses is not included in the sparse labels right? We should go back to the crowd-sourced data to add that information or was it done already?

**Comment by simondurand** [comment]
@ejhumphrey I started ticking what we already have. I think you can also add the checksums and maybe the metadata (what do you include in that metadata file?). 

How do we want to proceed for this issue? It is not like we can use Github to manage it.

Otherwise, for `class-map.json`, were you thinking of something like this?
```
{"accordion": 0, "banjo": 1, "bass": 2, "cello": 3, "clarinet": 4, "cymbals": 5, "drums": 6, "flute": 7, "guitar": 8, "mallet_percussion": 9, "mandolin": 10, "organ": 11, "piano": 12, "saxophone": 13, "synthesizer": 14, "trombone": 15, "trumpet": 16, "ukulele": 17, "violin": 18, "voice": 19}
```
