### ISSUE TITLE
Helper script to generate NumPy friendly data-structures

### ISSUE THREAD

**Issue by ejhumphrey** [cosmir/openmic-2018#8]
Inputs
- directory of VGGish JSON files
- Sparse Label CSV 

Outputs
- NPZ file, with the following keys
  - `X`: ndarray, shape=(20000, 10, 128), dtype=int8, values in [0, 255]
  - `Y_true`: ndarray, shape=(20000, 20), dtype=np.float32, values in [0, 1]), 
  - `Y_mask`: ndarray, shape=(20000, 20), dtype=bool, values in [0, 1] 
  - `sample_key`: nparray, shape=(20000,), dtype=object, values are strings

**Comment by simondurand** [comment]
@ejhumphrey To be sure, the values of `Y_true` are the conversion of the relevance scores in the crowdsourced experiments from the range `[-1, 1]` to the range `[0, 1]`, right?

**Comment by ejhumphrey** [comment]
as of #20, the relevance scores in the sparse label CSV file will already be bounded on [0, 1], and so it will be the case that `relevance == Y_true`

**Comment by ejhumphrey** [comment]
closed as of #18, but could use a final check on the comment above

**Comment by ejhumphrey** [comment]
closed as of #18, but could use a final check on the comment above
